"use strict";
const fs=require('fs'),path=require('path');
const {PATTERNS,PALETTE,pixels}=require('./icons');
const {encodePNG}=require('./lib/png');
const {hex}=require('./lib/canvas');
const root=path.join(__dirname,'../..');
let src='--!strict\n-- Generated by tools/pixelart/generate-icons.js; edit the hand-drawn grids in icons.js.\nexport type IconDef = { rows: { string }, palette: { [string]: Color3 } }\nlocal palette: { [string]: Color3 } = {\n';
for(const [k,v] of Object.entries(PALETTE))src+=`["${k}"] = Color3.fromHex("${v}"),\n`;
src+='}\nlocal icons: { [string]: IconDef } = {\n';
const entries=Object.entries(PATTERNS),width=8*96,height=Math.ceil(entries.length/8)*96;
const buf=Buffer.alloc(width*height*4);
for(let i=0;i<buf.length;i+=4){buf[i]=40;buf[i+1]=46;buf[i+2]=66;buf[i+3]=255;}
for(const [i,[name,pattern]] of entries.entries()){
 const rows=pixels(pattern); src+=`${name} = {palette = palette, rows = {${rows.map(r=>`"${r}"`).join(',')}}},\n`;
 for(let y=0;y<16;y++)for(let x=0;x<16;x++){
  const h=PALETTE[rows[y][x]];if(!h)continue;const c=hex(h);
  for(let sy=0;sy<4;sy++)for(let sx=0;sx<4;sx++){
   const o=((Math.floor(i/8)*96+16+y*4+sy)*width+(i%8)*96+16+x*4+sx)*4;
   buf[o]=c.r;buf[o+1]=c.g;buf[o+2]=c.b;buf[o+3]=255;
  }
 }
}
src+='}\nreturn { Size = 16, icons = icons }\n';
fs.writeFileSync(path.join(root,'src/client/UI/PixelIcons.luau'),src);
fs.mkdirSync(path.join(root,'art/ui'),{recursive:true});
fs.writeFileSync(path.join(root,'art/ui/icons.png'),encodePNG(width,height,buf));
console.log(`Generated ${entries.length} pixel icons`);
