"use strict";
// Maps already uploaded Roblox image IDs to v2 atlases. Never uploads or changes old IDs.
const fs=require('fs'),path=require('path');
const root=path.join(__dirname,'../..');
const file=process.argv[2];
const allowIncomplete=process.argv.includes('--allow-incomplete');
if(!file)throw Error('Usage: node tools/pixelart/import-arcade.js asset-ids.json');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'art/sprites/v3/manifest.json'),'utf8'));
const input=JSON.parse(fs.readFileSync(file,'utf8'));
const previous=JSON.parse(fs.readFileSync(path.join(root,'art/sprites/v2/asset-ids.json'),'utf8'));
const retired=new Set(['rook','brakk','sable'].flatMap(id=>Array.from({length:6},(_,i)=>previous[`${id}_${i+1}.png`]).filter(Boolean)));
for(const [name,value] of Object.entries(input))if(retired.has(String(value).replace(/^rbxassetid:\/\//,'')))throw Error(`${name}: previous outfit ID cannot be used for the newly clothed atlas`);
const allowed=new Set(Object.values(manifest.characters).flatMap(c=>c.files));
for(const key of Object.keys(input))if(!allowed.has(key))throw Error('Unknown atlas: '+key);
const target=path.join(root,'src/shared/Config/CharacterSpriteUploads.luau');
const current=fs.readFileSync(target,'utf8');
const entries={};
for(const m of current.matchAll(/(\w+)\s*=\s*\{([^}]+)\}/g)){
 const ids=[...m[2].matchAll(/"(rbxassetid:\/\/\d+)"/g)].map(v=>v[1]);if(ids.length===6)entries[m[1]]=ids;
}
let updated=0;
for(const [id,c] of Object.entries(manifest.characters)){
 const values=c.files.map(f=>input[f]);
 if(values.every(v=>v===undefined||v===''))continue;
 if(values.some(v=>v!==undefined&&v!==''&&(typeof v!=='string'||! /^(rbxassetid:\/\/)?[1-9]\d*$/.test(v))))throw Error(`${id}: invalid image ID`);
 const missing=c.files.filter((f,i)=>values[i]===undefined||values[i]==='');
 if(missing.length&&allowIncomplete){console.log(`Waiting for ${id}: ${missing.join(', ')}`);continue;}
 if(values.some(v=>typeof v!=='string'||! /^(rbxassetid:\/\/)?[1-9]\d*$/.test(v)))throw Error(`${id}: supply all six positive image IDs as strings`);
 entries[id]=values.map(v=>v.startsWith('rbxassetid://')?v:'rbxassetid://'+v);updated++;
}
if(!updated)throw Error('No complete character uploads provided; configuration unchanged');
const text='--!strict\n-- Generated by tools/pixelart/import-arcade.js from uploaded image IDs.\nlocal uploads: { [string]: { string } } = {\n'+Object.entries(entries).map(([id,ids])=>`${id} = {${ids.map(v=>JSON.stringify(v)).join(',')}},`).join('\n')+'\n}\nreturn uploads\n';
fs.writeFileSync(target,text);console.log(`Connected ${updated} characters; ${Object.keys(entries).length}/16 total`);
